### ISSUE TITLE
Botinfo 

### ISSUE THREAD

**Issue by Hiekki4** [stardiscordbot/starbot#11]
Faz um botinfo ai,

**Comment by yADGithub** [comment]
https://github.com/yADGithub/starbot/blob/developer/src/commands/Others/BotinfoCommand.js

**Comment by Hiekki4** [comment]
Atualiza o botinfo

**Comment by yADGithub** [comment]
mas enfim, em breve eu faço um botinfo

**Comment by yADGithub** [comment]
Fechando issue
