### ISSUE TITLE
Otimizar

### ISSUE THREAD

**Issue by Follow-w** [stardiscordbot/starbot#12]
Quando vai excluir os arquivos desnecessários n entendi o porquê de dar require no quote

**Comment by euandrelucas** [comment]
para não encher o arquivo de linhas 👍

**Comment by euandrelucas** [comment]
mais algo ou posso fechar o issue?

**Comment by eiandremoreira** [comment]
Não é desnecessário

Imagina em cada comando ter 155 linhas so de quote n dah né
