### ISSUE TITLE
Utilização de .bat em bots.

### ISSUE THREAD

**Issue by algebraic-dev** [stardiscordbot/starbot#4]
Devido a meu Sistema operacional atual, Arch linux, não suportar a execução de BatchScripts, já que é feito para windows, acho bom colocar arquivos Bash para a execução do bot. É isso, fica a sugestão para os proximos dias, meses ou anos.

**Comment by euandrelucas** [comment]
enfim, esses arquivos são mais para mim mesmo, para testes, para eu não ter que abrir o vsc pra fazer um teste por exemplo, e tem pessoas que não sabem usar o terminal ai ela só executa o ".bat" já que muitos tem o OS windows

**Comment by algebraic-dev** [comment]
Sim mas de certo modo, voce pode usar o package.json pra introduzir esses comandos e rodar usando o npm ou o yarn. Isso é mais idiomatico e deixa mais simples do que fazer .bat ou .sh
