### ISSUE TITLE
código mal organizado e formulado

### ISSUE THREAD

**Issue by 2vitor** [stardiscordbot/starbot#47]
olhando um pouco do código, eu percebi que, o código não está muito bem organizado.
  - o uso de arquivos ***.mjs** é desnecessário, colocando `"type": "module"` na package.json já ativa o esmodules ~~(import/export)~~
  - arquivos sem uso algum (erishard, por exemplo)
  - `starshard.mjs` usa `discord.js-light` em um projeto feito com ***eris***?
  - na linha 35 do arquivo src/client/handler/comandos.js o código poderia ser reduzido muito, já que, está usando try catch no readdir (que é assícrono, ou seja, `.catch()`) /https://github.com/stardiscordbot/starbot/blob/bac2804406c2e3919d7b495ef77de782bea5719e/src/client/handler/comandos.js#L35
  entre outros problemas.

       eu não vi todo o código, mas acho que refazer o projeto em algumas partes pode ajudar bastante a entender o que ocorre dentro do código :smiley: 
lembrando que meu objetivo é só ajudar o projeto.

> Software de código aberto é o software de computador com o seu código fonte disponibilizado e licenciado com uma licença de código aberto no qual o direito autoral fornece o direito de estudar, modificar e distribuir o software de graça para qualquer um e para qualquer finalidade. 
(Wikipedia)

<br></br>
_fui banido do servidor por nada..? id 338025459654590465_

**Comment by davipatricio** [comment]
up.

**Comment by liy77** [comment]
Eu não mexo na star, porém o arquivo mjs é necessario, pois ao colocar type: "module" na package.json, ira ativar o esmodules para todos os arquivos assim deixando de aceitar o require e não possibilitando o funcionamento do handler.

**Comment by 2vitor** [comment]
> Eu não mexo na star, porém o arquivo mjs é necessario, pois ao colocar type: "module" na package.json, ira ativar o esmodules para todos os arquivos assim deixando de aceitar o require e não possibilitando o funcionamento do handler.

é só usar import(). retorna uma Promise, então vai precisar usar await, then, ou qualquer outra coisa do gênero para tratar a Promise

**Comment by euandrelucas** [comment]
obrigado pelo issue
