### ISSUE TITLE
SetTimeout 

### ISSUE THREAD

**Issue by spotbli** [stardiscordbot/starbot#7]
Seria bacana se colocasse o daily sem ser settimeout com `Date.now()`
Se o bot reiniciar as pessoas conseguem pegar o daily novamente, com o `Date.now()` fica salvo o tempo do daily no banco de dados mongodb

**Comment by euandrelucas** [comment]
obrigado pelo issue, estou resolvendo isso

**Comment by eiandremoreira** [comment]
Resolvido
